<?php

/**
 * @file
 * Contains gdgourense.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gdgourense_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gdgourense module.
    case 'help.page.gdgourense':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demo de integración de Scrapy') . '</p>';
      return $output;

    default:
  }
}
